export const TESTBENCH_SCENARIOS = [
  "mock-ananke-registration",
  "mock-mnemosyne-registration",
  "incompatible-protocol-rejected",
  "irrelevant-capability-hidden",
  "unhealthy-runtime-excluded",
  "write-capability-routed-through-ananke",
  "memory-capability-routed-through-mnemosyne",
  "orchestration-event-emitted",
  "runtime-lifecycle-transition-validated",
  "task-owner-retained-during-degradation",
  "runtime-cancellation-and-deregistration",
  "failed-runtime-recovery",
  "heartbeat-freshness-assessment",
  "stale-heartbeat-degradation",
  "out-of-order-heartbeat-rejected",
];
